name: Deploy Resume

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, 
      # so your workflow can access it
      - name: check-out master branch
        uses: actions/checkout@master
      
      - name: Set up Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      
      - name: Install dependencies
        run: npm install

      - name: Build 
        run: npm run build

      # Copying files and artifacts via SSH
      - name: Copying files to server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.cluster002.hosting.ovh.net
          username: dotconsu
          password: ${{ secrets.ftp_password }}
          local-dir: dist/
          server-dir: www2/
